### ISSUE TITLE
running reidentify-DMR on the DMRfind results

### ISSUE THREAD

**Issue by FarzanehRah** [yupenghe/methylpy#85]
Hi,

I'm currently attempting to run `reidentify-DMR` on the` DMRfind` results. However, I encountered the following message, setting --sig-cutoff to 1 doesn't change anything:

```
Begin FDR Correction
Wed May 17 10:47:32 2023

m0 estimate for iteration 0: 0
Histogram FDR correction did not converge. Using the smallest p-value 0.0003333333333333333 as cutoff.

Calculating Residual Cutoff
Wed May 17 10:47:32 2023

There are no null residuals to calculate resid_cutoff. Using 2 as the cutoff.
Begin Defining Windows
Wed May 17 10:47:32 2023
```
Setting `--sig-cutoff` to 1 doesn't change anything. Additionally, when I attempt to set the `--resid-cutoff` parameter, I receive the following error:
`methylpy reidentify-DMR: error: argument --resid-cutoff: invalid int value: '0.05'`

Any advice or suggestions would be greatly appreciated.
Thanks

**Comment by yupenghe** [comment]
It was due to a bug in the code. It should be fixed in the latest version 1.4.7
Could you try it again after updating the methylpy version?

**Comment by FarzanehRah** [comment]
Thank you so much. Regarding the `--resid-cutoff,` I was able to define the value successfully. However, I'm still encountering an issue even after setting `--sig-cutoff` to 1:
`"m0 estimate for iteration 0: 0. Histogram FDR correction did not converge. Using the smallest p-value 0.0003333333333333333 as cutoff."`

**Comment by yupenghe** [comment]
Yes that usually means that the methylation difference the input samples is small and methylpy cannot find many DMSs/DMRs.

**Comment by FarzanehRah** [comment]
Thank you for your response. 
I'm curious if it would be possible to obtain some results by increasing the FDR threshold. Would that potentially yield some DMSs/DMRs? Additionally, I'm interested in understanding how we can change the smallest p-value (0.0003333333333333333) as the cutoff?

**Comment by yupenghe** [comment]
You can increase the number of simulations by assigning a larger number to `--num-sims`. Current default is 3000 and the smallest p-value equals to 1 / num_sims.

**Comment by FarzanehRah** [comment]
Thank you so much for your help.
